name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to the 'main' branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.4  # Correct Node.js version without quotes

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the static site with Supabase API keys as environment variables
      - name: Build static site
        run: npm run build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}  # Supabase environment variables
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      # Step 5: Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Vite’s default output directory is ./dist
