name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for Node.js-based builds

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run build
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      # Step 5: Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Output folder for Vite build (usually 'dist')
