name: Deploy Vite/React App to Scaleway Serverless Containers

on:
  push:
    branches:
      - documentation

env:
  SCW_DEFAULT_REGION: fr-par
  SCW_REGISTRY_NAMESPACE: namespace-new-webiste # Same as before, typo kept for consistency
  IMAGE_NAME: vite-react-app
  SCW_SERVERLESS_CONTAINER_ID: e8e42598-8860-45ee-8dc3-890fe00c972e

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.SCW_REGISTRY_NAMESPACE }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.SCW_REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.SCW_REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
            version: v2.39.0
            save-config: true
            export-config: true
            access-key: ${{ secrets.SCW_ACCESS_KEY }}
            secret-key: ${{ secrets.SCW_SECRET_KEY }}
            default-project-id: ${{ secrets.SCW_PROJECT_ID }}
            default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}

      - name: Deploy to Scaleway Serverless Container
        run: |
            IMAGE_URL="rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.SCW_REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
            echo "Updating container ${{ env.SCW_SERVERLESS_CONTAINER_ID }} → $IMAGE_URL"
            scw container container update ${{ env.SCW_SERVERLESS_CONTAINER_ID }} \
            registry-image=$IMAGE_URL \
            port=3000
            echo "Deployment triggered."
